### PR TITLE
Update no_resources.md

### PR DESCRIPTION
**Pull request by korbinib**
* Added vetinst
* reordered some items

### CODE REVIEW

**Comment by bedroesb** [comment]
@korbinib do I merge these changes + did you also apply these changes to the PR in the main IDTk repo?

**Comment by korbinib** [comment]
@Nazeeefa could decide wether this should be merged (and merged back?)

**Comment by Nazeeefa** [comment]
Thanks @korbinib! Just want to mention that we did think about adding CAMRIA (Combatting Antimicrobial Resistance with Interdisciplinary Approaches) under 'institutional initiatives' but didn't because it involves multiple organisations and as we understood that the initiative is for multiple regions, not specific to one location.

Would it be easier if future suggestions/changes are made in https://github.com/Nazeeefa/infectious-diseases-toolkit/blob/main/national-resources/norway.md ? just wondering, whatever you find easier :)

**Comment by bedroesb** [comment]
@Nazeeefa What do you think of merging this one and you copy over the content of the markdown here to the branch where you make a PR from in the "real" Infectious Diseases Toolkit?

**Comment by Nazeeefa** [comment]
Sounds good to merge it.

**Pull request merged**
